### ISSUE TITLE
Unable to find constants for AJAX requests

### ISSUE THREAD

**Issue by dtorio** [jncraton/PythonDropboxUploader#14]
Since yesterday upload_file raise this error again.

**Comment by jncraton** [comment]
Unfortunately, it looks like the Dropbox website has changed significantly under the hood. I'm afraid that I don't have time to fix this issue at the moment. If you get it figured out, please send a pull request.

**Comment by spitzbubchen** [comment]
Just discovered the same issue. I guess no fixes yet...

**Comment by scottsievert** [comment]
+1. Same issue.

**Comment by alfeinsod** [comment]
+1, me too

**Comment by karzanhi** [comment]
+1, Same problem here

**Comment by chinnababu** [comment]
Same issue :(

**Comment by jncraton** [comment]
This project used to interact with Dropbox using its website. This is hacky, hard to maintain, and is no longer fully possibly as Dropbox sometimes serves CAPTCHAs on certain requests. Dropbox has had a complete Python API for a long time now. I'd recommend using that instead:

https://www.dropbox.com/developers/documentation/python

If you just want something that can quickly let you use Dropbox from a terminal, I'd recommend rclone:

https://rclone.org/
