### ISSUE TITLE
Master Branch Broken

### ISSUE THREAD

**Issue by gdxn96** [jncraton/PythonDropboxUploader#16]
init.py line 3 ImportError, no module named upload. If I installed wrong, it is from a lack of instructions.

**Comment by jncraton** [comment]
Sorry about that. I don't really maintain this project anymore. It used to interact directly with the Dropbox website front end, but site changes made it difficult to keep working. Dropbox has an official Python API that I'd highly recommend instead:

https://www.dropbox.com/developers/core/start/python
