### ISSUE TITLE
mechanize._response.httperror_seek_wrapper: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by chinnababu** [jncraton/PythonDropboxUploader#18]
Fixed the issue as "Unable to find constants for AJAX requests" by changing the constant values, then I got above error while submitting the login page at line 76 . Please help me. Thank you in advance.

**Comment by jncraton** [comment]
This project used to interact with Dropbox using its website. This is hacky, hard to maintain, and is no longer fully possibly as Dropbox sometimes serves CAPTCHAs on certain requests. Dropbox has had a complete Python API for a long time now. I'd recommend using that instead:

https://www.dropbox.com/developers/documentation/python

If you just want something that can quickly let you use Dropbox from a terminal, I'd recommend rclone:

https://rclone.org/
