### ISSUE TITLE
Error: Unable to find constants for AJAX requests

### ISSUE THREAD

**Issue by robbielj** [jncraton/PythonDropboxUploader#2]
PDU has been working normally until a few days ago.

This is the raised exception.

**Comment by Chipmunk-djng** [comment]
I see this error again. Raises this error at line 86 in dbupload/dbconn.py

**Comment by alfeinsod** [comment]
I am getting this same error on line 86 in dbupload/dbconn.py

**Comment by Chipmunk-djng** [comment]
Yes, this error occurs because Dropbox has changed the response. The easier and robust solution to this problem is to use the official Dropbox API.
